sudo: false
language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=gcc-6 CC=gcc-6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - libxcb-dev

    - os: linux
      env: COMPILER_NAME=gcc CXX=gcc-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - libxcb-dev

    - os: linux
      env: COMPILER_NAME=clang++ CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
            - libxcb-dev

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.7
            - libxcb-dev

    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.6 CC=clang-3.6
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libxcb-dev

before_script:
  - mkdir -p build
  - cd build

script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=
  - cmake -DCMAKE_BUILD_TYPE=Debug .. && make

